POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pa28iLCJpZCI6IjY4OWRjYTI0ZjI3MWQ5MzU0ZDM4MTMyYSIsImlhdCI6MTc1NTE3MzcyMX0.gHl4oPNBVsHszxE3sEo5zs_s5MDKFcy9n391cJO9MQw

{
  "title": "test title of a blog by logged in user",
  "author": "logged in user",
  "url": "test url",
  "likes": 1
}
